# Generated by Django 4.0.1 on 2022-03-18 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtkc', '0029_auto_20211226_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='start_course',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 13, 6, 28, 16, 995168)),
        ),
    ]
